# Wrangler configuration for Cloudflare Pages
name = "atrocitee-astro"
compatibility_date = "2023-06-14"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables 
# Define non-secret environment variables here
[vars]
PUBLIC_SUPABASE_URL = "https://ssvvvpedcdyssmojaoln.supabase.co"
PUBLIC_SHOW_DEBUG = "false"
PRINTFUL_SANDBOX_MODE = "false"
ENABLE_TEST_MODE = "false"
PRINTFUL_API_BASE_URL = "https://api.printful.com"

# Preview environment variables
[env.preview]
# vars = { PUBLIC_SUPABASE_URL = "https://your-staging-project.supabase.co" }

# For sensitive values, use secrets:
# To set: npx wrangler secret put PUBLIC_SUPABASE_ANON_KEY

# KV namespace for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "1d2d30b2c22e494884a106265b67e6ae"
# preview_id = "your-kv-namespace-id-for-preview" 