name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run astro check

      - name: Lint code
        run: |
          # If you have ESLint configured:
          # npm run lint
          # For now, just checking if the build works
          npm run build

  build:
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # If you want to add additional checks like Lighthouse, add them here:
      # - name: Lighthouse audit
      #   uses: treosh/lighthouse-ci-action@v9
      #   with:
      #     urls: |
      #       https://preview-url-from-cloudflare.pages.dev/
      #     budgetPath: ./budget.json
      #     uploadArtifacts: true 